---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ci-cd
  labels:
    app: cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
        - name: golang
          image: dipugodocker/test-go:1.0
          resources:
            requests:
              cpu: "500m"
              memory: "200Mi"
            limits:
              cpu: "800m"
              memory: "400Mi"
        - name: c-lang
          image: dipugodocker/test-c:1.0
          resources:
            requests:
              cpu: "500m"
              memory: "200Mi"
            limits:
              cpu: "800m"
              memory: "400Mi"
...