---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ci-cd
  labels:
    app: cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
        - name: mywebsite
          image: dipugodocker/weatherapp:v2
          resources:
            requests:
              cpu: "500m"
              memory: "200Mi"
            limits:
              cpu: "800m"
              memory: "400Mi"
          livenessProbe:
            exec:
              command:
                - cat
                - /usr/share/nginx/html/index.html
          readinessProbe:
            httpGet:
              path: /
              port: 80
          ports:
            - containerPort: 80
...